export const dataTest = [
  {
    month: "01",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "02",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "03",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran 03",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "04",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran 04",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "05",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran 05",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "06",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran 06",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "07",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran 07",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
  {
    month: "08",
    data: [
      {
        id: 1,
        name: "Tranh cup mở rộng Albert Tran 08",
        address: "Sân Mai Động\nSân Hoàng Mai",
        address_closing: "Sân Mai Động",
        start_date_register: "25/12/2023",
        end_date_register: "31/12/2023",
        start_date: "01/01/2024",
        end_date: "31/01/2024",
        draw_date: "01/01/2024",
        banner:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb3285b440_banner.png",
        url_qr:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32a5d105_logo.png",
        url_logo:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images/658bb32c5c957_logo.png",
        url_pdf:
          "https://cms-viettennis.tdev.vn/vtn/uploads/tournaments/images",
        total_prize: "150000000",
        sponsor: "AlbertTran",
        secret_key: "1234",
        note: null,
        overview:
          "<p>MỤC Đ&Iacute;CH, Y&Ecirc;U CẦU</p>\n\n<p>1. Mục đ&iacute;ch</p>\n\n<p>C&aacute;c đơn vị, Vận động vi&ecirc;n chấp h&agrave;nh tốt c&aacute;c quy định của Điều lệ v&agrave; của<br />\nBan Tổ chức như: Đối tượng thi đấu, thời gian, thủ tục đăng k&yacute;, luật....</p>\n\n<p>Giải tổ chức phải an to&agrave;n, tiết kiệm, c&oacute; hiệu quả v&agrave; chất lượng cao.</p>\n\n<p>Thi đấu đo&agrave;n kết, trung thực, cao thượng.<br />\n2. Y&ecirc;u cầu</p>\n\n<p>II. ĐƠN VỊ TỔ CHỨC,<br />\nTHỜI GIAN, ĐỊA ĐIỂM</p>\n\n<p>1. Đơn vị tổ chức giải đấu<br />\n- Diễn đ&agrave;n Vieennis.net &ndash; Vieennis Huế.</p>\n\n<p>2. Thời gian đăng k&yacute;<br />\nTừ trước thời hạn đăng k&yacute; đến 17h00 ng&agrave;y 07/08/2023.<br />\n(C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng thời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải).</p>\n\n<p>3. Thời gian bốc thăm: 9h00 ng&agrave;y 08/08/2023<br />\n- Nhận đăng k&yacute; thi đấu đến 17h00 ng&agrave;y 08/08/2023. C&aacute;c đơn vị kh&ocirc;ng gửi đăng k&yacute; danh s&aacute;ch đ&uacute;ng<br />\nthời gian qui định tr&ecirc;n sẽ kh&ocirc;ng được tham gia giải.<br />\n- Mời Trưởng đo&agrave;n hoặc Huấn luyện vi&ecirc;n trưởng của c&aacute;c đơn vị, C&acirc;u lạc bộ họp chuy&ecirc;n m&ocirc;n, bốc<br />\nthăm (thay giấy mời) v&agrave;o l&uacute;c 9h00 ng&agrave;y 08/08/2023 tại nh&agrave; h&agrave;ng Sline 59 L&acirc;m Hoằng.</p>\n\n<p>4. Thời gian thi đấu &amp; bế mạc<br />\n- Thời gian thi đấu: Từ ng&agrave;y 10/08/2023 đến ng&agrave;y 13/08/2023.<br />\n- L&ecirc; khai mạc: 17h ng&agrave;y 11/08/2023, tại s&acirc;n quần vợt An Cựu City, Th&agrave;nh phố Huế.<br />\n- Lễ Bế mạc: Gala (Nh&agrave; h&agrave;ng Sline) tại Cụm s&acirc;n An Cựu City : 18h ng&agrave;y 13/08/2023.</p>\n\n<p>5. Địa điểm thi đấu<br />\n+ Cụm S&acirc;n Quần vợt An Cựu City Huế.<br />\n+ Cụm S&acirc;n Quần vợt Trung t&acirc;m hoạt động<br />\nthanh thiếu ni&ecirc;n 57 L&acirc;m Hoằng.</p>\n\n<p>+ Cụm S&acirc;n Quần vợt 100 Phạm Văn Đồng.<br />\n+ Cụm S&acirc;n Xăng Dầu &ndash; Tỉnh lộ 10.</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang tập luyện v&agrave;<br />\nsinh hoạt diễn đ&agrave;n Vieennis.net.</p>\n\n<p>* Khi đăng k&yacute; thi đấu c&aacute;c VĐV phải cung cấp đầy đủ th&ocirc;ng tin : Diễn đ&agrave;n đang sinh hoạt, tr&igrave;nh điểm, nick, số<br />\nđiện thoại, ảnh ch&acirc;n dung.<br />\n* Trường hợp c&aacute;c VĐV kh&ocirc;ng c&oacute; điểm &ndash; Ban tổ chức kh&ocirc;ng nắm r&otilde; tr&igrave;nh vận động vi&ecirc;n th&igrave; c&oacute; quyền từ chối<br />\nnhận đăng k&yacute; thi đấu.</p>\n\n<p>Vận động vi&ecirc;n c&aacute;c tỉnh theo<br />\nthư mời của Ban Tổ chức giải.</p>\n\n<p>III. ĐỐI TƯỢNG THAM GIA</p>\n\n<p>C&aacute;c vận động vi&ecirc;n đang sinh hoạt tại<br />\nc&aacute;c CLB Quần vợt tr&ecirc;n địa b&agrave;n tỉnh<br />\nThừa Thi&ecirc;n Huế.</p>",
        status: 1,
        link_facebook: null,
        link_youtube: null,
        created_at: "2023-12-27T05:16:38.000000Z",
        surface: 1,
        surface_name: "Sân cứng",
        province_id: 24,
        district_id: 253,
        ward_id: "",
        province_name: "Hà Nội",
        district_name: "Quận Hoàng Mai",
        ward_name: "",
        status_name: "Hoạt động",
        tournaments: [
          {
            id: 1,
            parent_id: 1,
            type: 1,
            template: 10,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1200,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
          {
            id: 2,
            parent_id: 1,
            type: 1,
            template: 11,
            cost: 3000000,
            banner: "",
            gender_type: 2,
            rank_point: 1300,
            rank_point_type: 1,
            created_by: 1,
            updated_by: null,
            created_at: "26/12/2023",
            updated_at: "26/12/2023",
            deleted_by: null,
            deleted_at: null,
          },
        ],
      },
    ],
  },
];
