export const html = `<p>Một vấn đề c&ograve;n tồn đọng tại TPHCM li&ecirc;n quan đến sự l&atilde;ng ph&iacute; quỹ đất v&agrave; việc thu&ecirc; cho c&aacute;c mục đ&iacute;ch kh&ocirc;ng ph&ugrave; hợp trong c&aacute;c khu c&ocirc;ng nghiệp v&agrave; khu chế xuất. Thậm ch&iacute;, c&ograve;n c&oacute; t&igrave;nh trạng x&acirc;y dựng sai ph&eacute;p k&eacute;o d&agrave;i m&agrave; chưa được giải quyết một c&aacute;ch triệt hạ.</p>

<h2>Ngăn chặn kịp thời t&igrave;nh trạng l&atilde;ng ph&iacute; đất</h2>

<p>Kết quả r&agrave; so&aacute;t, thanh tra từ năm 2018 đến 2020, ri&ecirc;ng tại Ban Quản l&yacute; Khu c&ocirc;ng nghệ cao (KCNC) đ&atilde; lập hồ sơ điều chỉnh cục bộ quy hoạch chi tiết 1/2000 giai đoạn 1 v&agrave; giai đoạn 2. Tuy nhi&ecirc;n Thanh tra TPHCM ph&aacute;t hiện một số nội dung chưa ph&ugrave; hợp quy hoạch chung được cấp thẩm quyền ph&ecirc; duyệt. Ban Quản l&yacute; KCNC đ&atilde; c&oacute; nhiều thiếu s&oacute;t, vi phạm li&ecirc;n quan đến trật tự x&acirc;y dựng, cho thu&ecirc; đất, quản l&yacute;&nbsp;<a href="https://nhadatvui.vn/tin-tuc/tai-chinh" target="_blank">t&agrave;i ch&iacute;nh</a>... Việc thiếu s&oacute;t quản l&yacute; trật tự x&acirc;y dựng theo quy hoạch v&agrave; sau cấp ph&eacute;p x&acirc;y dựng đối với một số chủ đầu tư dự &aacute;n đ&atilde; khiến KCNC xảy ra t&igrave;nh trạng x&acirc;y dựng sai ph&eacute;p chậm khắc phục (Nh&agrave; m&aacute;y Jabil Việt Nam, Trung t&acirc;m C&ocirc;ng nghệ H&agrave;ng kh&ocirc;ng, C&ocirc;ng ty TNHH MTV C&ocirc;ng nghệ cao Điện Quang, Tổng C&ocirc;ng ty C&ocirc;ng nghiệp S&agrave;i G&ograve;n TNHH MTV).</p>

<p><img src="https://file.maumau.vn/public/nhadatvui/0/1691811116737/6560dc36-37c0-4a3a-87ec-e34871bdfc32.jpg" /></p>

<p>Khu c&ocirc;ng nghiệp Binh Duong Industrial Park</p>

<p>Những năm gần đ&acirc;y, Thanh tra Ch&iacute;nh phủ đ&atilde; nhiều lần y&ecirc;u cầu UBND TPHCM b&aacute;o c&aacute;o hướng xử l&yacute; thực trạng ở nhiều doanh nghiệp thu&ecirc; đất trong c&aacute;c khu c&ocirc;ng nghiệp (KCN), khu chế xuất (KCX) nhưng kh&ocirc;ng đưa v&agrave;o khai th&aacute;c sử dụng, để đất trống k&eacute;o d&agrave;i nhiều năm, dẫn đến l&atilde;ng ph&iacute; t&agrave;i nguy&ecirc;n đất. Chỉ t&iacute;nh ri&ecirc;ng ở KCN Hiệp Phước trong giai đoạn thanh tra đ&atilde; ph&aacute;t hiện c&ograve;n trống 41.767,6m2. KCN L&ecirc; Minh Xu&acirc;n 7.273,72m2. KCN T&acirc;n B&igrave;nh khoảng 4.000m2. Đi k&egrave;m với l&atilde;ng ph&iacute; trong quản l&yacute; quỹ đất, t&igrave;nh trạng chậm giải ph&oacute;ng mặt bằng được x&aacute;c định tổng diện t&iacute;ch l&ecirc;n đến gần 160ha, tập trung tại c&aacute;c KCN Cơ kh&iacute; &ocirc; t&ocirc; (9,88ha), KCN Hiệp Phước (giai đoạn 2, l&agrave; 40,4ha), KCN L&ecirc; Minh Xu&acirc;n (6,91ha), T&acirc;n Ph&uacute; Trung (52,6223ha), KCN T&acirc;n Tạo (hiện hữu 1,59ha, mở rộng l&agrave; 3,4ha)&hellip;</p>

<p>Được biết, kể từ giữa th&aacute;ng 5/2023, Ph&oacute; Thủ tướng Ch&iacute;nh phủ L&ecirc; Minh Kh&aacute;i đ&atilde; đồng &yacute; đề nghị của Bộ Kế hoạch v&agrave; Đầu tư về việc điều chỉnh, bổ sung c&aacute;c KCN tr&ecirc;n địa b&agrave;n&nbsp;<a href="https://nhadatvui.vn/mua-ban-nha-dat-tp-ho-chi-minh" target="_blank">TPHCM</a>&nbsp;v&agrave;o Quy hoạch ph&aacute;t triển c&aacute;c khu c&ocirc;ng nghiệp ở Việt Nam. Tuy nhi&ecirc;n, để kh&ocirc;ng xảy ra t&igrave;nh trạng l&atilde;ng ph&iacute; quỹ đất hoặc c&aacute;c bất cập, hạn chế c&aacute;c tranh chấp, khiếu kiện trong qu&aacute; tr&igrave;nh triển khai thực hiện quy hoạch, TPHCM cần đảm bảo sự ph&ugrave; hợp, t&iacute;nh khả thi, li&ecirc;n kết, đồng bộ; đảm bảo điều kiện, tr&igrave;nh tự, thủ tục giao đất, cho thu&ecirc; đất, cho ph&eacute;p chuyển mục đ&iacute;ch sử dụng đất theo quy định của ph&aacute;p luật, kh&ocirc;ng l&agrave;m thất tho&aacute;t t&agrave;i sản nh&agrave; nước.</p>

<p>Trong khi đ&oacute;, theo &ocirc;ng Phạm Thanh Trực (Ph&oacute; Trưởng Ban Quản l&yacute; c&aacute;c KCX, KCN), hiện TPHCM c&oacute; 16 KCN v&agrave; 3 KCX hoạt động, với tổng diện t&iacute;ch khoảng 4.500ha, tỉ lệ lấp đầy đạt hơn 81%, đ&oacute;ng g&oacute;p t&iacute;ch cực v&agrave;o tăng trưởng kinh tế của th&agrave;nh phố trong nhiều năm qua. C&aacute;c KCX, KCN tr&ecirc;n địa b&agrave;n đ&atilde; đ&oacute;ng g&oacute;p v&agrave;o ng&acirc;n s&aacute;ch nh&agrave; nước hơn 22.000 tỷ đồng v&agrave; giải quyết việc l&agrave;m cho hơn 281.000 lao động của TPHCM v&agrave; nhiều địa phương kh&aacute;c tới th&agrave;nh phố l&agrave;m việc.</p>

<h2>Nguy cơ thiếu hịt nguồn lao động</h2>

<p>Trong khi c&ograve;n t&igrave;nh trạng l&atilde;ng ph&iacute; về quỹ đất, nhiều KCN, KCX của TPHCM c&ograve;n gặp kh&oacute; khăn khi thiếu hụt lao động.</p>

<p><img src="https://file.maumau.vn/public/nhadatvui/0/1680772401988/d6060047-7cdf-401c-b0b8-196da4693843.jpg" /></p>

<p>Khu c&ocirc;ng nghiệp Đồng Văn IV</p>

<p>Tại buổi gặp gỡ, đối thoại của Ban Quản l&yacute; c&aacute;c KCX, KCN mới đ&acirc;y, đại diện C&ocirc;ng ty TNHH MTV KCN Vĩnh Lộc đ&atilde; phản &aacute;nh t&igrave;nh trạng thiếu hụt lao động của nhiều DN. Đồng thời đề xuất được ch&iacute;nh quyền địa phương v&agrave; Ban Quản l&yacute; c&aacute;c KCX, KCN c&oacute; giải ph&aacute;p hỗ trợ vấn đề an ninh trật tự cho lực lượng c&ocirc;ng nh&acirc;n tại c&aacute;c khu vực nh&agrave; trọ xung quanh KCN.</p>

<p>Theo &ocirc;ng Đ&agrave;o Xu&acirc;n Đức - Ph&oacute; Chủ tịch Hiệp hội c&aacute;c doanh nghiệp KCN, c&aacute;c vướng mắc, kh&oacute; khăn trong việc &ldquo;giữ ch&acirc;n&rdquo; c&ocirc;ng nh&acirc;n l&agrave; vấn đề thời sự. Việc x&acirc;y dựng nơi lưu tr&uacute; v&agrave; dịch vụ hạ tầng phục vụ c&ocirc;ng nh&acirc;n cần phải được ch&uacute; trọng, trong đ&oacute; triển khai c&aacute;c dự &aacute;n về nh&agrave; ở x&atilde; hội, nh&agrave; lưu tr&uacute; để phục vụ c&ocirc;ng nh&acirc;n, người lao động tỉnh về th&agrave;nh phố l&agrave;m việc. B&ecirc;n cạnh đ&oacute;, cũng cần quan t&acirc;m hơn về c&aacute;c vấn đề an ninh trật tự, xử l&yacute; r&aacute;c thải, giao th&ocirc;ng, giải quyết t&igrave;nh trạng b&aacute;n h&agrave;ng rong cũng như c&aacute;c vấn đề an sinh li&ecirc;n quan đến c&ocirc;ng nh&acirc;n, người lao động...</p>

<p>Viện Nghi&ecirc;n cứu ph&aacute;t triển TPHCM được giao nghi&ecirc;n cứu đề &aacute;n &ldquo;Định hướng ph&aacute;t triển c&ocirc;ng nghiệp TPHCM đến năm 2030, tầm nh&igrave;n đến năm 2050&rdquo;, trong đ&oacute; c&oacute; định hướng về th&iacute; điểm chuyển đổi c&aacute;c KCN. Y&ecirc;u cầu t&aacute;i cấu tr&uacute;c c&aacute;c KCN, KCX l&agrave; tất yếu để hạn chế những ng&agrave;nh nghề, lĩnh vực th&acirc;m dụng lao động. B&ecirc;n cạnh đ&oacute; cần tiếp cận nhanh với xu hướng ph&aacute;t triển c&ocirc;ng nghiệp mới, nhất l&agrave; việc thu h&uacute;t c&aacute;c ng&agrave;nh nghề, lĩnh vực c&ocirc;ng nghệ cao, c&oacute; năng suất lao động, h&agrave;m lượng tri thức cao...v&agrave;o c&aacute;c KCN, KCX hiện hữu của th&agrave;nh phố.</p>`;
